### ISSUE TITLE
Broken Recordings link

### ISSUE THREAD

**Issue by nsk126** [prgumd/TTCDist#1]
The link to download recordings to be placed in `TTCDist/recordings_21_11_12` doesn't seem to be working. 
I found the paper on arxiv and wanted to test it out.

**Comment by aftersomemath** [comment]
Hi, sorry for the delay, I did not receive an email about this GitHub issue for some reason.

I just tried tested downloading the data in a "incognito" browser window and the data downloaded successfully. Could you try again? Maybe there was a temporary issue with Google Drive.

**Comment by nsk126** [comment]
Seems to be working now. Thank you so much! I was really interested in the paper you've written.

**Comment by aftersomemath** [comment]
Thank you!
